#!/usr/bin/env ruby

require 'whois'

TLD = '.me'

File.open("./en.txt") do |file|
  file.each_with_index do |line, index|
    word = line.strip

    # different requirements for the word
    next if index < 1000 # start after this index
    next if word.length <= 3
    next if word.length >= 7

    # Don't run it too often
    sleep 1 + rand(2)

    domain = "#{word}#{TLD}"
    puts domain if Whois.available?(domain)
  end
end
